# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8e2a4771b6320a61cb5c1bfa10f2f27f4d5d186158b1ee82ed4c5093f9e40bb6cffdb5d07518c46d1552ad2acbdc425dab14aa1db24c560bb4700c65e1f8c0

test:
  secret_key_base: 91859b8917e05add72baac5603f7a665c4e8c4be3e38962197e9588f29e24c427aba16a88d22c8da77fea54a4aa23401857eec14ffcc06d5eabd6d4a1cd905f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
